# Generated by Django 4.2.16 on 2025-03-27 04:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('farm', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='motor',
            name='UIN',
            field=models.PositiveIntegerField(null=True),
        ),
    ]
