# Generated by Django 4.2.16 on 2025-03-20 11:01

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Motor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('UIN', models.CharField(max_length=15, unique=True)),
                ('TYPE', models.CharField(choices=[('REQ', 'Required'), ('OPT', 'Optional')], default='REQ', max_length=3)),
                ('VCOUNT', models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(10)])),
                ('STATUS', models.CharField(choices=[('Working', 'Working'), ('Maintenance', 'Under Maintenance'), ('Failed', 'Failed'), ('Idle', 'Idle')], default='Working', max_length=20)),
                ('LOCATION', models.CharField(max_length=50)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Valve',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('valve_number', models.PositiveIntegerField()),
                ('value', models.CharField(default='0', max_length=10)),
                ('motor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='valves', to='motors.motor')),
            ],
            options={
                'ordering': ['valve_number'],
                'unique_together': {('motor', 'valve_number')},
            },
        ),
    ]
