# Generated by Django 4.2.16 on 2025-03-20 16:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('motors', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='valve',
            name='last_operated_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
