# Generated by Django 4.2.16 on 2025-03-20 17:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('motors', '0002_valve_last_operated_at'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='valve',
            name='last_operated_at',
        ),
    ]
