# Generated by Django 4.2.16 on 2025-03-21 04:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('motors', '0003_remove_valve_last_operated_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='valve',
            name='last_operated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='valve',
            name='value',
            field=models.CharField(choices=[('0', 'Off'), ('1', 'On')], default='0', max_length=10),
        ),
    ]
