# Generated by Django 4.2.16 on 2025-03-21 04:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('motors', '0004_valve_last_operated_at_alter_valve_value'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='motor',
            name='LOCATION',
        ),
    ]
